/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Pedidos;

/**
 *
 * @author cesar
 */
public class PanelFecha extends javax.swing.JPanel {

    
    public PanelFecha(int dia, int noOrden, int cantidad,String descTipoProceso) {
        initComponents();
        lbFecha.setText(dia+"");
        if(noOrden > 0){
            lbOP.setText(noOrden+"");
            lbCantidad.setText(cantidad+"");
            lbTipoProceso.setText(descTipoProceso);
        }else{
            lbNameCANT.setText("");
            lbNameOP.setText("");
            lbtituloProceso.setText("");
        }
            
    }

    public PanelFecha(int dia) {
        initComponents();
        lbFecha.setText(dia+"");
        lbNameCANT.setText("");
        lbNameOP.setText("");
        lbtituloProceso.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbOP = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        lbNameOP = new javax.swing.JLabel();
        lbCantidad = new javax.swing.JLabel();
        lbNameCANT = new javax.swing.JLabel();
        lbtituloProceso = new javax.swing.JLabel();
        lbTipoProceso = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);
        add(lbOP);
        lbOP.setBounds(65, 4, 43, 19);
        add(lbFecha);
        lbFecha.setBounds(3, 4, 32, 17);

        lbNameOP.setText("OP");
        add(lbNameOP);
        lbNameOP.setBounds(32, 4, 30, 19);
        add(lbCantidad);
        lbCantidad.setBounds(42, 36, 66, 17);

        lbNameCANT.setText("CANT");
        add(lbNameCANT);
        lbNameCANT.setBounds(3, 36, 32, 16);

        lbtituloProceso.setText("PROCESO");
        add(lbtituloProceso);
        lbtituloProceso.setBounds(3, 60, 105, 16);

        lbTipoProceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lbTipoProceso);
        lbTipoProceso.setBounds(3, 83, 102, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbNameCANT;
    private javax.swing.JLabel lbNameOP;
    private javax.swing.JLabel lbOP;
    private javax.swing.JLabel lbTipoProceso;
    private javax.swing.JLabel lbtituloProceso;
    // End of variables declaration//GEN-END:variables
}
